//! Reader for LaTeX output generated by `marksmen-latex`.
//!
//! Reconstructs Markdown-like text by applying heuristic replacements
//! to basic LaTeX commands generated by marksmen-latex. This does NOT
//! constitute a full TeX parser.

use anyhow::Result;

pub fn parse_latex(text: &str) -> Result<String> {
    // Basic extraction loop to find content between \begin{document} and \end{document}
    let body = extract_document_body(text);

    // Simplistic text replacement mapping LaTeX tags back to markdown
    let mut mapped = body.to_string();

    // Headers
    mapped = mapped.replace("\\section{", "\n# ");
    mapped = mapped.replace("\\subsection{", "\n## ");
    mapped = mapped.replace("\\subsubsection{", "\n### ");
    mapped = mapped.replace("\\paragraph{", "\n#### ");
    mapped = mapped.replace("\\subparagraph{", "\n##### ");

    // Formatting
    mapped = mapped.replace("\\textbf{", "**");
    mapped = mapped.replace("\\textit{", "*");
    mapped = mapped.replace("\\sout{", "~~");
    mapped = mapped.replace("\\texttt{", "`");

    // Since we just replaced the opening commands with markdown tags but left the trailing '}'
    // we need to somehow strip matched closing braces.
    // For a robust implementation, a proper parser is required.
    // Here we just naively clear all naked trailing braces that were attached to formatting tags.
    // However, to keep it simple and safe for math tags, we will just use a simplistic custom pass.

    // Footnotes
    mapped = mapped.replace("\\footnotemark[", "[^");
    mapped = replace_footnotetext(&mapped);

    // Figures
    mapped = extract_figures(&mapped);

    // Tables
    mapped = extract_tables(&mapped);

    Ok(process_replacements(&mapped))
}

fn replace_footnotetext(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(idx) = rest.find("\\footnotetext[") {
        out.push_str(&rest[..idx]);
        out.push_str("\n\n[^");
        rest = &rest[idx + "\\footnotetext[".len()..];
        if let Some(close) = rest.find("]{") {
            out.push_str(&rest[..close]);
            out.push_str("]: ");
            rest = &rest[close + 2..];
        }
    }
    out.push_str(rest);
    out
}

fn extract_figures(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = rest.find("\\begin{figure}") {
        out.push_str(&rest[..start]);
        let end_fig = rest[start..]
            .find("\\end{figure}")
            .unwrap_or(rest.len() - start)
            + start;
        let fig_body = &rest[start..end_fig];
        rest = &rest[end_fig + "\\end{figure}".len()..];

        let mut url = "";
        let mut title = "";

        if let Some(ig_start) = fig_body.find("\\includegraphics") {
            let after_ig = &fig_body[ig_start..];
            if let Some(brace_start) = after_ig.find('{')
                && let Some(brace_end) = after_ig[brace_start..].find('}')
            {
                url = &after_ig[brace_start + 1..brace_start + brace_end];
            }
        }

        if let Some(cap_start) = fig_body.find("\\caption{") {
            let after_cap = &fig_body[cap_start + "\\caption{".len()..];
            if let Some(cap_end) = after_cap.find('}') {
                title = &after_cap[..cap_end];
            }
        }

        out.push_str(&format!("![{}]({})\n\n", title, url));
    }
    out.push_str(rest);
    out
}

fn extract_tables(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = rest.find("\\begin{longtable}{") {
        out.push_str(&rest[..start]);
        rest = &rest[start + "\\begin{longtable}{".len()..];

        let align_end = rest.find('}').unwrap_or(0);
        let align_str = &rest[..align_end];
        rest = &rest[align_end + 1..];

        let end_table = rest.find("\\end{longtable}").unwrap_or(rest.len());
        let table_body = &rest[..end_table];
        rest = &rest[end_table + "\\end{longtable}".len()..];

        let mut header = String::new();
        let mut body = table_body.to_string();

        if let Some(mid) = body.find("\\midrule\n") {
            header = body[..mid].to_string();
            body = body[mid + "\\midrule\n".len()..].to_string();
        }

        header = header.replace("\\toprule\n", "");
        body = body.replace("\\bottomrule\n", "");

        let clean_row = |mut r: &str| -> String {
            r = r.trim();
            if r.ends_with("\\\\") {
                r = r[..r.len() - 2].trim();
            }
            let mut s = r.replace("\\&", "MARKSMEN_ESCAPED_AMP");
            s = s.replace("&", " | ");
            s = s.replace("MARKSMEN_ESCAPED_AMP", "\\&");
            s = s.replace("\\\\\n", " |\n| ");
            s = s.replace("\\\\", " |\n| ");
            s
        };

        out.push('\n');
        out.push('|');
        out.push(' ');
        out.push_str(&clean_row(&header));
        out.push_str(" |\n|");

        for c in align_str.chars() {
            match c {
                'l' => out.push_str(" :--- |"),
                'c' => out.push_str(" :---: |"),
                'r' => out.push_str(" ---: |"),
                _ => out.push_str(" --- |"),
            }
        }
        out.push('\n');

        out.push('|');
        out.push(' ');
        out.push_str(&clean_row(&body));
        out.push_str(" |\n\n");
    }
    out.push_str(rest);
    out
}

fn extract_document_body(text: &str) -> &str {
    let begin_doc = "\\begin{document}";
    let end_doc = "\\end{document}";
    if let Some(start) = text.find(begin_doc) {
        let offset = start + begin_doc.len();
        if let Some(end) = text.find(end_doc)
            && offset < end
        {
            return text[offset..end].trim();
        }
    }
    text
}

// A stateful character pass to drop closing braces and balance them, and handle blocks
fn process_replacements(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut chars = text.chars().peekable();

    let mut brace_depth = 0;

    // Very rudimentary parser to strip closing braces for formatting tags that were converted
    while let Some(c) = chars.next() {
        if c == '\\'
            && let Some(&n) = chars.peek()
        {
            if n == '\\' {
                chars.next();
                out.push('\n'); // convert \\ to newline
                continue;
            } else if matches!(n, '%' | '$' | '#' | '_' | '{' | '}' | '&') {
                chars.next();
                out.push(n);
                continue;
            }
        }

        if c == '{' {
            brace_depth += 1;
            out.push('{');
        } else if c == '}' {
            if brace_depth > 0 {
                brace_depth -= 1;
                out.push('}');
            } else {
                // Orphan brace likely from a replaced command \textbf{ -> ** ... } => **...
                // we drop it.
                // Note: this is a huge simplification but fits the lightweight requirement.
            }
        } else {
            out.push(c);
        }
    }

    // Simple block replacements
    let mut res = out;
    res = res.replace("\\begin{quote}", "> ");
    res = res.replace("\\end{quote}", "");
    res = res.replace("\\begin{itemize}", "");
    res = res.replace("\\end{itemize}", "");
    res = res.replace("\\begin{enumerate}", "");
    res = res.replace("\\end{enumerate}", "");
    res = res.replace("\\item", "-");
    res = res.replace("\\begin{lstlisting}", "```");
    res = res.replace("\\end{lstlisting}", "```");

    res.trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_read_latex() {
        let tex = "\\begin{document}\n\\section{Hello}\nTest paragraph.\n\\end{document}";
        let md = parse_latex(tex).unwrap();
        assert!(md.contains("# Hello"));
        assert!(md.contains("Test paragraph."));
    }
}
