//! Reader for LaTeX output generated by `marksmen-latex`.
//!
//! Reconstructs Markdown-like text by applying heuristic replacements
//! to basic LaTeX commands generated by marksmen-latex. This does NOT
//! constitute a full TeX parser.

use anyhow::Result;

pub fn parse_latex(text: &str) -> Result<String> {
    // Basic extraction loop to find content between \begin{document} and \end{document}
    let body = extract_document_body(text);

    // Simplistic text replacement mapping LaTeX tags back to markdown
    let mut mapped = body.to_string();

    // Headers
    mapped = mapped.replace("\\section{", "\n# ");
    mapped = mapped.replace("\\subsection{", "\n## ");
    mapped = mapped.replace("\\subsubsection{", "\n### ");
    mapped = mapped.replace("\\paragraph{", "\n#### ");
    mapped = mapped.replace("\\subparagraph{", "\n##### ");

    // Formatting
    mapped = mapped.replace("\\textbf{", "**");
    mapped = mapped.replace("\\textit{", "*");
    mapped = mapped.replace("\\sout{", "~~");
    mapped = mapped.replace("\\texttt{", "`");

    // Since we just replaced the opening commands with markdown tags but left the trailing '}'
    // we need to somehow strip matched closing braces.
    // For a robust implementation, a proper parser is required.
    // Here we just naively clear all naked trailing braces that were attached to formatting tags.
    // However, to keep it simple and safe for math tags, we will just use a simplistic custom pass.

    Ok(process_replacements(&mapped))
}

fn extract_document_body(text: &str) -> &str {
    let begin_doc = "\\begin{document}";
    let end_doc = "\\end{document}";
    if let Some(start) = text.find(begin_doc) {
        if let Some(end) = text.find(end_doc) {
            let offset = start + begin_doc.len();
            if offset < end {
                return text[offset..end].trim();
            }
        }
    }
    text
}

// A stateful character pass to drop closing braces and balance them, and handle blocks
fn process_replacements(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut chars = text.chars().peekable();

    let mut brace_depth = 0;

    // Very rudimentary parser to strip closing braces for formatting tags that were converted
    while let Some(c) = chars.next() {
        if c == '\\' {
            if let Some(&n) = chars.peek() {
                if n == '\\' {
                    chars.next();
                    out.push('\n'); // convert \\ to newline
                    continue;
                } else if n == '%'
                    || n == '$'
                    || n == '#'
                    || n == '_'
                    || n == '{'
                    || n == '}'
                    || n == '&'
                {
                    chars.next();
                    out.push(n);
                    continue;
                }
            }
        }

        if c == '{' {
            brace_depth += 1;
            out.push('{');
        } else if c == '}' {
            if brace_depth > 0 {
                brace_depth -= 1;
                out.push('}');
            } else {
                // Orphan brace likely from a replaced command \textbf{ -> ** ... } => **...
                // we drop it.
                // Note: this is a huge simplification but fits the lightweight requirement.
            }
        } else {
            out.push(c);
        }
    }

    // Simple block replacements
    let mut res = out;
    res = res.replace("\\begin{quote}", "> ");
    res = res.replace("\\end{quote}", "");
    res = res.replace("\\begin{itemize}", "");
    res = res.replace("\\end{itemize}", "");
    res = res.replace("\\begin{enumerate}", "");
    res = res.replace("\\end{enumerate}", "");
    res = res.replace("\\item", "-");
    res = res.replace("\\begin{lstlisting}", "```");
    res = res.replace("\\end{lstlisting}", "```");

    res.trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_read_latex() {
        let tex = "\\begin{document}\n\\section{Hello}\nTest paragraph.\n\\end{document}";
        let md = parse_latex(tex).unwrap();
        assert!(md.contains("# Hello"));
        assert!(md.contains("Test paragraph."));
    }
}
