//! Reader for HTML output generated by `marksmen-html`.
//!
//! Reconstructs Markdown-like text by traversing the HTML body and restoring
//! headings, paragraphs, lists, tables, code blocks, math spans, images, and
//! hidden roundtrip metadata blocks.

use anyhow::{Context, Result};
use scraper::{ElementRef, Html, Node, Selector};

pub fn parse_html(html: &str) -> Result<String> {
    let document = Html::parse_document(html);
    let body_selector = Selector::parse("body").unwrap();
    let body = document
        .select(&body_selector)
        .next()
        .context("HTML document missing <body>")?;

    let mut out = String::new();
    for child in body.children() {
        render_node(child, &mut out, false);
    }

    Ok(cleanup_markdown(&out))
}

fn render_node(handle: ego_tree::NodeRef<'_, Node>, out: &mut String, in_pre: bool) {
    match handle.value() {
        Node::Text(text) => {
            if in_pre {
                out.push_str(text);
            } else {
                let normalized = text.text.to_string();
                let mut compressed = String::with_capacity(normalized.len());
                let mut in_space = false;
                for c in normalized.chars() {
                    if c.is_whitespace() {
                        if !in_space { compressed.push(' '); in_space = true; }
                    } else {
                        compressed.push(c);
                        in_space = false;
                    }
                }
                if !compressed.is_empty() {
                    out.push_str(&compressed);
                }
            }
        }
        Node::Element(element) => {
            let Some(el) = ElementRef::wrap(handle) else { return };
            let name = element.name();
            match name {
                "h1" | "h2" | "h3" | "h4" | "h5" | "h6" => {
                    let level = name[1..].parse::<usize>().unwrap_or(1);
                    ensure_block_break(out);
                    out.push_str(&"#".repeat(level));
                    out.push(' ');
                    render_children(&el, out, false);
                    out.push_str("\n\n");
                }
                "p" => {
                    ensure_block_break(out);
                    render_children(&el, out, false);
                    out.push_str("\n\n");
                }
                "blockquote" => {
                    ensure_block_break(out);
                    let mut inner = String::new();
                    render_children(&el, &mut inner, false);
                    for line in cleanup_markdown(&inner).lines() {
                        out.push_str("> ");
                        out.push_str(line);
                        out.push('\n');
                    }
                    out.push('\n');
                }
                "strong" => {
                    out.push_str("**");
                    render_children(&el, out, false);
                    out.push_str("**");
                }
                "em" => {
                    out.push('*');
                    render_children(&el, out, false);
                    out.push('*');
                }
                "del" => {
                    out.push_str("~~");
                    render_children(&el, out, false);
                    out.push_str("~~");
                }
                "code" => {
                    out.push('`');
                    render_children(&el, out, true);
                    out.push('`');
                }
                "pre" => {
                    let class = element.attr("class").unwrap_or_default();
                    if class.contains("marksmen-roundtrip-meta") {
                        ensure_block_break(out);
                        render_children(&el, out, true);
                        out.push_str("\n\n");
                    } else {
                        ensure_block_break(out);
                        out.push_str("```\n");
                        render_children(&el, out, true);
                        out.push_str("\n```\n\n");
                    }
                }
                "span" => {
                    let class = element.attr("class").unwrap_or_default();
                    if class.contains("math-inline") {
                        out.push('$');
                        render_children(&el, out, true);
                        out.push('$');
                    } else {
                        render_children(&el, out, false);
                    }
                }
                "div" => {
                    let class = element.attr("class").unwrap_or_default();
                    if class.contains("math-display") {
                        ensure_block_break(out);
                        out.push_str("$$\n");
                        render_children(&el, out, true);
                        out.push_str("\n$$\n\n");
                    } else if class.contains("mermaid-graph") {
                        // Visible rendered graph is skipped; hidden metadata block carries source.
                    } else {
                        render_children(&el, out, false);
                    }
                }
                "a" => {
                    let href = element.attr("href").unwrap_or_default();
                    let mut label = String::new();
                    render_children(&el, &mut label, false);
                    out.push('[');
                    out.push_str(label.trim());
                    out.push_str("](");
                    out.push_str(href);
                    out.push(')');
                }
                "img" => {
                    let alt = element.attr("alt").unwrap_or("Image");
                    let src = element.attr("src").unwrap_or_default();
                    out.push_str(&format!("![{}]({})", alt, src));
                }
                "br" => out.push('\n'),
                "hr" => {
                    ensure_block_break(out);
                    out.push_str("---\n\n");
                }
                "ul" => {
                    ensure_block_break(out);
                    for li in el.children().filter_map(ElementRef::wrap).filter(|child| child.value().name() == "li") {
                        out.push_str("- ");
                        let mut item = String::new();
                        render_children(&li, &mut item, false);
                        out.push_str(item.trim());
                        out.push('\n');
                    }
                    out.push('\n');
                }
                "ol" => {
                    ensure_block_break(out);
                    for (idx, li) in el.children().filter_map(ElementRef::wrap).filter(|child| child.value().name() == "li").enumerate() {
                        out.push_str(&(idx + 1).to_string());
                        out.push_str(". ");
                        let mut item = String::new();
                        render_children(&li, &mut item, false);
                        out.push_str(item.trim());
                        out.push('\n');
                    }
                    out.push('\n');
                }
                "table" => {
                    ensure_block_break(out);
                    render_table(&el, out);
                    out.push('\n');
                }
                "thead" | "tbody" | "tr" | "td" | "th" => {}
                _ => render_children(&el, out, in_pre),
            }
        }
        _ => {}
    }
}

fn render_children(el: &ElementRef<'_>, out: &mut String, in_pre: bool) {
    for child in el.children() {
        render_node(child, out, in_pre);
    }
}

fn render_table(table: &ElementRef<'_>, out: &mut String) {
    let row_selector = Selector::parse("tr").unwrap();
    let cell_selector = Selector::parse("th, td").unwrap();
    let rows: Vec<Vec<String>> = table
        .select(&row_selector)
        .map(|row| {
            row.select(&cell_selector)
                .map(|cell| {
                    let mut inner = String::new();
                    render_children(&cell, &mut inner, false);
                    cleanup_markdown(&inner)
                })
                .collect::<Vec<_>>()
        })
        .filter(|row| !row.is_empty())
        .collect();

    if rows.is_empty() {
        return;
    }

    out.push('|');
    for cell in &rows[0] {
        out.push(' ');
        out.push_str(cell.trim());
        out.push_str(" |");
    }
    out.push('\n');
    out.push('|');
    for _ in &rows[0] {
        out.push_str(" :--- |");
    }
    out.push('\n');

    for row in rows.iter().skip(1) {
        out.push('|');
        for cell in row {
            out.push(' ');
            out.push_str(cell.trim());
            out.push_str(" |");
        }
        out.push('\n');
    }
}

fn ensure_block_break(out: &mut String) {
    if out.is_empty() {
        return;
    }
    if !out.ends_with("\n\n") {
        if out.ends_with('\n') {
            out.push('\n');
        } else {
            out.push_str("\n\n");
        }
    }
}

fn cleanup_markdown(input: &str) -> String {
    let mut cleaned = input.replace("\r\n", "\n").replace('\r', "\n");
    while cleaned.contains("\n\n\n") {
        cleaned = cleaned.replace("\n\n\n", "\n\n");
    }
    cleaned.trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::parse_html;

    #[test]
    fn parses_math_and_mermaid_metadata() {
        let html = r#"<!DOCTYPE html><html><body>
<h2>Section</h2>
<p>Alpha <span class="math-inline">x+y</span></p>
<div class="math-display">z^2</div>
<div class="mermaid-graph"><svg></svg></div>
<pre class="marksmen-roundtrip-meta" style="display:none">```mermaid
flowchart LR
A --> B
```</pre>
</body></html>"#;
        let parsed = parse_html(html).unwrap();
        assert!(parsed.contains("## Section"));
        assert!(parsed.contains("$x+y$"));
        assert!(parsed.contains("$$\nz^2\n$$"));
        assert!(parsed.contains("```mermaid"));
    }
}
