//! Mathematical similarity validation for round-trip document parsing.
//!
//! Enforces that semantic structures (equations, lists, tables) generated by `marksmen-core`
//! and exported to OOXML/ODF formats can be reliably parsed back into Markdown ASTs without
//! empirical degradation.

use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

/// Helper function to locate `demo.md` from the workspace root
fn get_workspace_root() -> PathBuf {
    let mut path = std::env::current_dir().unwrap();
    // In tests, current_dir is the crate directory
    if path.ends_with("crates") || path.ends_with("marksmen-roundtrip") {
        path.pop();
        if path.ends_with("crates") {
            path.pop();
        }
    }
    path
}

/// Synthetically strips YAML frontmatter arrays `---...---` to isolate
/// the Jaro-Winkler similarity coefficient onto the mathematical formatting bounds itself.
fn strip_frontmatter(md: &str) -> String {
    let mut lines = md.lines();
    if let Some(first) = lines.next() {
        if first == "---" {
            // consume until next ---
            for line in lines.by_ref() {
                if line == "---" {
                    break;
                }
            }
        } else {
            return md.to_string(); // not frontmatter
        }
    }
    lines.collect::<Vec<_>>().join("\n")
}

fn strip_mermaid(md: &str) -> String {
    let mut out = String::new();
    let mut in_mermaid = false;
    for line in md.lines() {
        if line.starts_with("```mermaid") {
            in_mermaid = true;
            continue;
        }
        if in_mermaid && line.starts_with("```") {
            in_mermaid = false;
            continue;
        }
        if !in_mermaid {
            out.push_str(line);
            out.push('\n');
        }
    }
    out.trim().to_string()
}

fn strip_vectors_and_html(s: &str) -> String {
    // Basic regex-like stripping without bringing in regex crate
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    let mut in_image_bracket = false;
    let mut in_image_paren = false;
    let mut chars = s.chars().peekable();
    
    while let Some(c) = chars.next() {
        if c == '<' {
            in_tag = true;
            continue;
        } else if c == '>' && in_tag {
            in_tag = false;
            continue;
        } else if in_tag {
            continue;
        }
        
        if c == '!' && chars.peek() == Some(&'[') {
            in_image_bracket = true;
            chars.next(); // Eat '['
            continue;
        } else if c == ']' && in_image_bracket {
            in_image_bracket = false;
            // Next should be '('
            if chars.peek() == Some(&'(') {
                in_image_paren = true;
                chars.next(); // Eat '('
            }
            continue;
        } else if c == ')' && in_image_paren {
            in_image_paren = false;
            continue;
        } else if in_image_bracket || in_image_paren {
            continue;
        }
        
        out.push(c);
    }
    out
}

fn normalize_whitespace(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut last_was_space = false;
    for c in s.chars() {
        if c.is_whitespace() {
            if !last_was_space {
                out.push(' ');
                last_was_space = true;
            }
        } else {
            out.push(c);
            last_was_space = false;
        }
    }
    out.trim().to_string()
}

#[test]
fn test_docx_roundtrip_similarity() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    
    // 1. Setup Source Text
    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    // 2. Compile to DOCX natively
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    
    // Provide a dummy path for image resolution
    let docx_bytes = marksmen_docx::translation::document::convert(events, &config, &get_workspace_root())?;

    // 3. Extract back to Markdown string
    let extracted_md = marksmen_docx_read::parse_docx(&docx_bytes)?;
    // 4. Mathematical Similarity Threshold
    let normalized_source = normalize_whitespace(&strip_vectors_and_html(&strip_frontmatter(&demo_md)));
    let normalized_extracted = normalize_whitespace(&strip_vectors_and_html(&extracted_md));
    std::fs::write("docx_norm_src.txt", &normalized_source).unwrap();
    std::fs::write("docx_norm_ext.txt", &normalized_extracted).unwrap();
    
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("DOCX Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);
    
    // The DOCX format has two known structural limitations that cap achievable similarity:
    //   1. Trailing-space stripping: OOXML <w:t> elements require xml:space="preserve" to
    //      retain significant whitespace; without it, XML processors strip leading/trailing
    //      spaces from runs (e.g. the space before an italic span is lost on extraction).
    //   2. Italic-context interruption: inline code spans (`…`) inside an italic paragraph
    //      must be emitted as non-italic runs.  The reader then re-opens the italic marker
    //      for each surrounding run, producing *text* `code` *more text* instead of the
    //      canonical *text `code` more text*.  Both representations are semantically
    //      equivalent but differ character-for-character.
    // These two effects together introduce a measurable but bounded deficit of ~0.0017 JW.
    assert!(
        jw_sim > 0.945,
        "DOCX round-trip extraction degraded below 0.945 similarity threshold (Actual: {:.4})",
        jw_sim
    );

    Ok(())
}

#[test]
fn test_odt_roundtrip_similarity() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    
    // 1. Setup Source Text
    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    // 2. Compile to ODT natively
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    
    let odt_bytes = marksmen_odt::translate_and_render(&events, &config, root)?;

    // 3. Extract back to Markdown string
    let extracted_md = marksmen_odt_read::parse_odt(&odt_bytes)?;
    fs::write(root.join("extracted_odt.md"), &extracted_md)?;

    // 4. Mathematical Similarity Threshold
    let normalized_source = normalize_whitespace(&strip_vectors_and_html(&strip_frontmatter(&demo_md)));
    let normalized_extracted = normalize_whitespace(&strip_vectors_and_html(&strip_frontmatter(&extracted_md)));
    std::fs::write("odt_norm_src.txt", &normalized_source).unwrap();
    std::fs::write("odt_norm_ext.txt", &normalized_extracted).unwrap();
    
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("ODT Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);
    
    assert!(
        jw_sim > 0.80,
        "ODT round-trip extraction degraded below 0.80 similarity threshold (Actual: {:.4})",
        jw_sim
    );

    Ok(())
}

#[test]
fn test_html_roundtrip_similarity() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));

    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    let source_md_stripped = strip_frontmatter(&demo_md);

    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);

    let html = marksmen_html::convert(events, &config)?;
    let extracted_md = marksmen_html_read::parse_html(&html)?;

    let normalized_source = normalize_whitespace(&strip_vectors_and_html(&source_md_stripped));
    let normalized_extracted = normalize_whitespace(&strip_vectors_and_html(&extracted_md));
    std::fs::write("html_norm_src.txt", &normalized_source).unwrap();
    std::fs::write("html_norm_ext.txt", &normalized_extracted).unwrap();

    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("HTML Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);

    assert!(
        jw_sim > 0.90,
        "HTML round-trip extraction degraded below 0.90 similarity threshold (Actual: {:.4})",
        jw_sim
    );

    Ok(())
}

#[test]
fn test_pdf_roundtrip_similarity() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    
    // 1. Setup Source Text
    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    let source_md_stripped = strip_mermaid(&strip_frontmatter(&demo_md));

    // 2. Compile to PDF natively
    let config = marksmen_core::Config::default();
    let pdf_bytes = marksmen_pdf::convert(&demo_md, &config, Some(root.join("../../").into()))?;

    // 3. Extract back to text string
    let extracted_md = marksmen_pdf_read::parse_pdf(&pdf_bytes)?;

    // 4. Mathematical Similarity Threshold
    let normalized_source = strip_vectors_and_html(&normalize_whitespace(&source_md_stripped));
    // Extraction does not contain mermaid tags or frontmatter, but stripping is safe.
    let normalized_extracted = strip_vectors_and_html(&normalize_whitespace(&extracted_md));
    std::fs::write("pdf_norm_src.txt", &normalized_source).unwrap();
    std::fs::write("pdf_norm_ext.txt", &normalized_extracted).unwrap();
    
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("PDF Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);
    
    // PDF text extraction is fundamentally lossy, often degrading to ~0.7-0.9 depending on layout.
    assert!(
        jw_sim > 0.70,
        "PDF round-trip extraction degraded below 0.70 similarity threshold (Actual: {:.4})",
        jw_sim
    );

    Ok(())
}
/// Generates PDF, DOCX, and ODT outputs from `demo.md` into `tests/snapshots/` and creates
/// a browser-viewable HTML index so that formatting can be inspected visually.
///
/// Run with: `cargo test test_visual_snapshots -- --nocapture`
#[test]
fn test_visual_snapshots() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let snapshots_dir = root.join("tests/snapshots");
    fs::create_dir_all(&snapshots_dir)?;

    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    let config = marksmen_core::Config::default();

    // ── PDF ──────────────────────────────────────────────────────────────────
    let pdf_bytes = marksmen_pdf::convert(&demo_md, &config, Some(root.join("../../").into()))?;
    assert!(
        pdf_bytes.starts_with(b"%PDF"),
        "Generated output does not have PDF magic bytes"
    );
    // A full document with images/math should comfortably exceed 50 KiB.
    assert!(
        pdf_bytes.len() > 50_000,
        "PDF output is suspiciously small ({} bytes) — likely missing content",
        pdf_bytes.len()
    );
    let pdf_path = snapshots_dir.join("demo_output.pdf");
    fs::write(&pdf_path, &pdf_bytes)?;
    println!("PDF  → {} ({} bytes)", pdf_path.display(), pdf_bytes.len());

    // ── DOCX ─────────────────────────────────────────────────────────────────
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let events = marksmen_core::parsing::parser::parse(body);
    let docx_bytes = marksmen_docx::translation::document::convert(
        events,
        &config,
        &root.join("../../"),
    )?;
    // DOCX is a ZIP archive; magic bytes are PK (0x50 0x4B).
    assert!(
        docx_bytes.starts_with(&[0x50, 0x4B]),
        "Generated output does not have DOCX/ZIP magic bytes"
    );
    let docx_path = snapshots_dir.join("demo_output.docx");
    fs::write(&docx_path, &docx_bytes)?;
    println!("DOCX → {} ({} bytes)", docx_path.display(), docx_bytes.len());

    // ── ODT ──────────────────────────────────────────────────────────────────
    let (body2, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let events2 = marksmen_core::parsing::parser::parse(body2);
    let odt_bytes = marksmen_odt::translate_and_render(&events2, &config, &root.join("../../"))?;
    assert!(
        odt_bytes.starts_with(&[0x50, 0x4B]),
        "Generated output does not have ODT/ZIP magic bytes"
    );
    let odt_path = snapshots_dir.join("demo_output.odt");
    fs::write(&odt_path, &odt_bytes)?;
    println!("ODT  → {} ({} bytes)", odt_path.display(), odt_bytes.len());

    // ── HTML viewer ──────────────────────────────────────────────────────────
    // Writes a simple browser-openable index so all three snapshots can be
    // inspected side by side.  Open tests/snapshots/index.html in any browser.
    let viewer_html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Marksmen Roundtrip Snapshots</title>
  <style>
    body {{ font-family: sans-serif; margin: 2rem; background: #f5f5f5; }}
    h1 {{ color: #333; }}
    .grid {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 1rem; margin-top: 1rem; }}
    .card {{ background: white; border-radius: 6px; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,.15); }}
    h2 {{ margin: 0 0 .5rem; font-size: 1rem; color: #555; }}
    iframe {{ width: 100%; height: 600px; border: 1px solid #ddd; }}
    a.dl {{ display: inline-block; margin-top: .5rem; font-size: .85rem; color: #0366d6; }}
    .meta {{ font-size: .8rem; color: #888; margin-top: .25rem; }}
  </style>
</head>
<body>
  <h1>Marksmen Roundtrip Visual Snapshots</h1>
  <p>Generated from <code>demo.md</code> — open in a browser to inspect formatting.</p>
  <div class="grid">
    <div class="card">
      <h2>PDF Output</h2>
      <iframe src="demo_output.pdf" title="PDF Output"></iframe>
      <a class="dl" href="demo_output.pdf" download>Download PDF</a>
      <p class="meta">{pdf_bytes} bytes</p>
    </div>
    <div class="card">
      <h2>DOCX Output</h2>
      <p style="color:#666;font-size:.9rem">DOCX cannot be embedded in-browser. Download to inspect.</p>
      <a class="dl" href="demo_output.docx" download>Download DOCX</a>
      <p class="meta">{docx_bytes} bytes</p>
    </div>
    <div class="card">
      <h2>ODT Output</h2>
      <p style="color:#666;font-size:.9rem">ODT cannot be embedded in-browser. Download to inspect.</p>
      <a class="dl" href="demo_output.odt" download>Download ODT</a>
      <p class="meta">{odt_bytes} bytes</p>
    </div>
  </div>
</body>
</html>
"#,
        pdf_bytes = pdf_bytes.len(),
        docx_bytes = docx_bytes.len(),
        odt_bytes = odt_bytes.len(),
    );
    let viewer_path = snapshots_dir.join("index.html");
    fs::write(&viewer_path, viewer_html)?;
    println!("HTML → {} (open in browser for visual review)", viewer_path.display());

    Ok(())
}

/// Manual debugging aid — print the AST for an inline HTML snippet.
/// Run explicitly with: `cargo test test_ast_dump -- --ignored --nocapture`
#[test]
#[ignore]
fn test_ast_dump() {
    let md = "- **Underline**: <u style=\"color:red\">This text is underlined</u> via `<u>`";
    let events = marksmen_core::parsing::parser::parse(md);
    for e in &events {
        println!("{:?}", e);
    }
}

/// Manual debugging aid — extract `demo_test.docx` back to Markdown and save to
/// `extracted_manual.md`.  Requires `demo_test.docx` at the workspace root.
/// Run explicitly with: `cargo test test_manual_docx_extract -- --ignored --nocapture`
#[test]
#[ignore]
fn test_manual_docx_extract() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let docx_path = root.join("../../demo_test.docx");
    let bytes = std::fs::read(&docx_path)
        .unwrap_or_else(|_| panic!("demo_test.docx not found at {}", docx_path.display()));
    let text = marksmen_docx_read::parse_docx(&bytes).unwrap();
    let out = root.join("extracted_manual.md");
    std::fs::write(&out, &text).unwrap();
    println!("Written to {}", out.display());
}

/// Convert PRD/PRD.md to PDF and extract existing PRD DOCX files to MD.
#[test]
fn execute_prd_conversion() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../");
    println!("Workspace Root: {}", root.display());

    // 1. Convert PRD.md to PDF
    let prd_md_path = root.join("PRD/PRD.md");
    if prd_md_path.exists() {
        let prd_md_text = std::fs::read_to_string(&prd_md_path)?;
        let config = marksmen_core::Config::default();
        let pdf_bytes = marksmen_pdf::convert(&prd_md_text, &config, Some(root.join("PRD")))?;
        let pdf_out = root.join("PRD/PRD.pdf");
        std::fs::write(&pdf_out, pdf_bytes)?;
        println!("Compiled PRD.md -> {}", pdf_out.display());
    } else {
        println!("Warning: PRD/PRD.md not found.");
    }

    // 2. Convert Docx's to MD
    let docs = vec![
        "PRD/Product Requirement (PRD) - Transcranial 01.09.26 MS.docx",
        "PRD/Revised PRD Draft.docx",
    ];

    for doc in docs {
        let doc_path = root.join(doc);
        if doc_path.exists() {
            let bytes = std::fs::read(&doc_path)?;
            let md_text = marksmen_docx_read::parse_docx(&bytes)?;
            let md_out = doc_path.with_extension("md");
            std::fs::write(&md_out, md_text)?;
            println!("Extracted {} -> {}", doc, md_out.display());
        } else {
            println!("Warning: {} not found.", doc);
        }
    }

    Ok(())
}

#[test]
fn evaluate_prd_docx_roundtrip() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../");
    println!("Workspace Root: {}", root.display());

    let prd_md_path = root.join("PRD/PRD.md");
    if !prd_md_path.exists() {
        println!("Warning: PRD/PRD.md not found.");
        return Ok(());
    }

    let source_md = std::fs::read_to_string(&prd_md_path)?;
    
    // 1. Convert to DOCX
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&source_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    let docx_bytes = marksmen_docx::translation::document::convert(events, &config, &root.join("PRD"))?;

    // 2. Dump DOCX for manual reference
    let docx_out = root.join("PRD/prd.docx");
    std::fs::write(&docx_out, &docx_bytes)?;

    // 3. Extract back from DOCX to MD
    let extracted_md = marksmen_docx_read::parse_docx(&docx_bytes)?;
    
    // 4. Dump Markdown for discrepancy analysis
    let md_out = root.join("PRD/PRD_Roundtrip_Extracted.md");
    std::fs::write(&md_out, &extracted_md)?;

    let source_stripped = strip_mermaid(&strip_frontmatter(&source_md));
    let extracted_stripped = strip_mermaid(&strip_frontmatter(&extracted_md));

    let normalized_source = strip_vectors_and_html(&normalize_whitespace(&source_stripped));
    let normalized_extracted = strip_vectors_and_html(&normalize_whitespace(&extracted_stripped));

    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("PRD DOCX Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);

    std::fs::write(root.join("PRD/diff_norm_ext.txt"), &normalized_extracted)?;

    Ok(())
}

#[test]
fn test_html_conversion() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let demo_md = std::fs::read_to_string(root.join("../../demo.md"))?;
    
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    
    let html_string = marksmen_html::convert(events, &config)?;
    
    // Validate output bounds
    assert!(html_string.contains("<!DOCTYPE html>"), "Missing HTML DOCTYPE");
    assert!(html_string.contains("<svg"), "Missing inline Mermaid SVG injection");
    assert!(html_string.contains("<table"), "Missing Table parsing bounds");
    
    let snapshots_dir = root.join("tests/snapshots");
    std::fs::create_dir_all(&snapshots_dir)?;
    let html_out = snapshots_dir.join("demo_output_target.html");
    std::fs::write(&html_out, html_string)?;
    
    println!("HTML exported -> {}", html_out.display());
    Ok(())
}
