//! Mathematical similarity validation for round-trip document parsing.
//!
//! Enforces that semantic structures (equations, lists, tables) generated by `marksmen-core`
//! and exported to OOXML/ODF formats can be reliably parsed back into Markdown ASTs without
//! empirical degradation.

use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

/// Helper function to locate `demo.md` from the workspace root
fn get_workspace_root() -> PathBuf {
    let mut path = std::env::current_dir().unwrap();
    // In tests, current_dir is the crate directory
    if path.ends_with("crates") || path.ends_with("marksmen-roundtrip") {
        path.pop();
        if path.ends_with("crates") {
            path.pop();
        }
    }
    path
}

/// Synthetically strips YAML frontmatter arrays `---...---` to isolate
/// the Jaro-Winkler similarity coefficient onto the mathematical formatting bounds itself.
fn strip_frontmatter(md: &str) -> String {
    let mut lines = md.lines();
    if let Some(first) = lines.next() {
        if first == "---" {
            // consume until next ---
            for line in lines.by_ref() {
                if line == "---" {
                    break;
                }
            }
        } else {
            return md.to_string(); // not frontmatter
        }
    }
    lines.collect::<Vec<_>>().join("\n")
}

fn strip_mermaid(md: &str) -> String {
    let mut out = String::new();
    let mut in_mermaid = false;
    for line in md.lines() {
        if line.starts_with("```mermaid") {
            in_mermaid = true;
            continue;
        }
        if in_mermaid && line.starts_with("```") {
            in_mermaid = false;
            continue;
        }
        if !in_mermaid {
            out.push_str(line);
            out.push('\n');
        }
    }
    out.trim().to_string()
}

fn strip_vectors_and_html(s: &str) -> String {
    // Basic regex-like stripping without bringing in regex crate
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    let mut in_image_bracket = false;
    let mut in_image_paren = false;
    let mut chars = s.chars().peekable();
    
    while let Some(c) = chars.next() {
        if c == '<' {
            in_tag = true;
            continue;
        } else if c == '>' && in_tag {
            in_tag = false;
            continue;
        } else if in_tag {
            continue;
        }
        
        if c == '!' && chars.peek() == Some(&'[') {
            in_image_bracket = true;
            chars.next(); // Eat '['
            continue;
        } else if c == ']' && in_image_bracket {
            in_image_bracket = false;
            // Next should be '('
            if chars.peek() == Some(&'(') {
                in_image_paren = true;
                chars.next(); // Eat '('
            }
            continue;
        } else if c == ')' && in_image_paren {
            in_image_paren = false;
            continue;
        } else if in_image_bracket || in_image_paren {
            continue;
        }
        
        out.push(c);
    }
    out
}

fn normalize_whitespace(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut last_was_space = false;
    for c in s.chars() {
        if c.is_whitespace() {
            if !last_was_space {
                out.push(' ');
                last_was_space = true;
            }
        } else {
            out.push(c);
            last_was_space = false;
        }
    }
    out.trim().to_string()
}

#[test]
fn test_docx_roundtrip_similarity() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    
    // 1. Setup Source Text
    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    // 2. Compile to DOCX natively
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    
    // Provide a dummy path for image resolution
    let docx_bytes = marksmen_docx::translation::document::convert(events, &config, &get_workspace_root(), None)?;

    // 3. Extract back to Markdown string
    let extracted_md = marksmen_docx_read::parse_docx(&docx_bytes, None)?;
    // 4. Mathematical Similarity Threshold
    let normalized_source = normalize_whitespace(&strip_vectors_and_html(&strip_frontmatter(&demo_md)));
    let normalized_extracted = normalize_whitespace(&strip_vectors_and_html(&extracted_md));
    std::fs::write("docx_norm_src.txt", &normalized_source).unwrap();
    std::fs::write("docx_norm_ext.txt", &normalized_extracted).unwrap();
    
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("DOCX Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);
    
    // The DOCX format has two known structural limitations that cap achievable similarity:
    //   1. Trailing-space stripping: OOXML <w:t> elements require xml:space="preserve" to
    //      retain significant whitespace; without it, XML processors strip leading/trailing
    //      spaces from runs (e.g. the space before an italic span is lost on extraction).
    //   2. Italic-context interruption: inline code spans (`…`) inside an italic paragraph
    //      must be emitted as non-italic runs.  The reader then re-opens the italic marker
    //      for each surrounding run, producing *text* `code` *more text* instead of the
    //      canonical *text `code` more text*.  Both representations are semantically
    //      equivalent but differ character-for-character.
    // These two effects together introduce a measurable but bounded deficit of ~0.0017 JW.
    assert!(
        jw_sim > 0.945,
        "DOCX round-trip extraction degraded below 0.945 similarity threshold (Actual: {:.4})",
        jw_sim
    );

    Ok(())
}

#[test]
fn test_odt_roundtrip_similarity() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    
    // 1. Setup Source Text
    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    // 2. Compile to ODT natively
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    
    let odt_bytes = marksmen_odt::translate_and_render(&events, &config, root)?;

    // 3. Extract back to Markdown string
    let extracted_md = marksmen_odt_read::parse_odt(&odt_bytes)?;
    fs::write(root.join("extracted_odt.md"), &extracted_md)?;

    // 4. Mathematical Similarity Threshold
    let normalized_source = normalize_whitespace(&strip_vectors_and_html(&strip_frontmatter(&demo_md)));
    let normalized_extracted = normalize_whitespace(&strip_vectors_and_html(&strip_frontmatter(&extracted_md)));
    std::fs::write("odt_norm_src.txt", &normalized_source).unwrap();
    std::fs::write("odt_norm_ext.txt", &normalized_extracted).unwrap();
    
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("ODT Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);
    
    assert!(
        jw_sim > 0.80,
        "ODT round-trip extraction degraded below 0.80 similarity threshold (Actual: {:.4})",
        jw_sim
    );

    Ok(())
}

#[test]
fn test_html_roundtrip_similarity() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));

    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    let source_md_stripped = strip_frontmatter(&demo_md);

    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);

    let html = marksmen_html::convert(events, &config)?;
    let extracted_md = marksmen_html_read::parse_html(&html)?;

    let normalized_source = normalize_whitespace(&strip_vectors_and_html(&source_md_stripped));
    let normalized_extracted = normalize_whitespace(&strip_vectors_and_html(&extracted_md));
    std::fs::write("html_norm_src.txt", &normalized_source).unwrap();
    std::fs::write("html_norm_ext.txt", &normalized_extracted).unwrap();

    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("HTML Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);

    assert!(
        jw_sim > 0.90,
        "HTML round-trip extraction degraded below 0.90 similarity threshold (Actual: {:.4})",
        jw_sim
    );

    Ok(())
}

#[test]
fn test_pdf_roundtrip_similarity() -> Result<()> {
    let source_md = r#"---
title: PDF Roundtrip Sample
---
# Styled PDF Roundtrip

Alpha **beta** and *gamma* with `code`.

Inline math: $x+y$.

1. First item
2. Second item
"#;
    let source_md_stripped = strip_mermaid(&strip_frontmatter(source_md));

    // 2. Compile to PDF natively
    let config = marksmen_core::Config::default();
    let pdf_bytes = marksmen_pdf::convert(source_md, &config, None)?;

    // 3. Extract back to text string
    let extracted_md = marksmen_pdf_read::parse_pdf(&pdf_bytes)?;

    // 4. Mathematical Similarity Threshold
    let extracted_stripped = strip_mermaid(&strip_frontmatter(&extracted_md));
    let normalized_source = strip_vectors_and_html(&normalize_whitespace(&source_md_stripped));
    let normalized_extracted = strip_vectors_and_html(&normalize_whitespace(&extracted_stripped));
    std::fs::write("pdf_norm_src.txt", &normalized_source).unwrap();
    std::fs::write("pdf_norm_ext.txt", &normalized_extracted).unwrap();
    
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("PDF Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);
    
    // For marksmen-generated PDFs, the source Markdown is embedded into PDF metadata
    // and preferred by the reader, preserving style markers for roundtrip testing.
    // External PDFs still fall back to plain text extraction and remain lossy.
    assert!(
        jw_sim > 0.98,
        "PDF round-trip extraction degraded below 0.98 similarity threshold (Actual: {:.4})",
        jw_sim
    );

    Ok(())
}
/// Generates PDF, DOCX, and ODT outputs from `demo.md` into `tests/snapshots/` and creates
/// a browser-viewable HTML index so that formatting can be inspected visually.
///
/// Run with: `cargo test test_visual_snapshots -- --nocapture`
#[test]
fn test_visual_snapshots() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let snapshots_dir = root.join("tests/snapshots");
    fs::create_dir_all(&snapshots_dir)?;

    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    let config = marksmen_core::Config::default();

    // ── PDF ──────────────────────────────────────────────────────────────────
    let pdf_bytes = marksmen_pdf::convert(&demo_md, &config, Some(root.join("../../").into()))?;
    assert!(
        pdf_bytes.starts_with(b"%PDF"),
        "Generated output does not have PDF magic bytes"
    );
    // A full document with images/math should comfortably exceed 50 KiB.
    assert!(
        pdf_bytes.len() > 50_000,
        "PDF output is suspiciously small ({} bytes) — likely missing content",
        pdf_bytes.len()
    );
    let pdf_path = snapshots_dir.join("demo_output.pdf");
    fs::write(&pdf_path, &pdf_bytes)?;
    println!("PDF  → {} ({} bytes)", pdf_path.display(), pdf_bytes.len());

    // ── DOCX ─────────────────────────────────────────────────────────────────
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let events = marksmen_core::parsing::parser::parse(body);
    let docx_bytes = marksmen_docx::translation::document::convert(
        events,
        &config,
        &root.join("../../"),
        None,
    )?;
    // DOCX is a ZIP archive; magic bytes are PK (0x50 0x4B).
    assert!(
        docx_bytes.starts_with(&[0x50, 0x4B]),
        "Generated output does not have DOCX/ZIP magic bytes"
    );
    let docx_path = snapshots_dir.join("demo_output.docx");
    fs::write(&docx_path, &docx_bytes)?;
    println!("DOCX → {} ({} bytes)", docx_path.display(), docx_bytes.len());

    // ── ODT ──────────────────────────────────────────────────────────────────
    let (body2, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let events2 = marksmen_core::parsing::parser::parse(body2);
    let odt_bytes = marksmen_odt::translate_and_render(&events2, &config, &root.join("../../"))?;
    assert!(
        odt_bytes.starts_with(&[0x50, 0x4B]),
        "Generated output does not have ODT/ZIP magic bytes"
    );
    let odt_path = snapshots_dir.join("demo_output.odt");
    fs::write(&odt_path, &odt_bytes)?;
    println!("ODT  → {} ({} bytes)", odt_path.display(), odt_bytes.len());

    // ── HTML viewer ──────────────────────────────────────────────────────────
    // Writes a simple browser-openable index so all three snapshots can be
    // inspected side by side.  Open tests/snapshots/index.html in any browser.
    let viewer_html = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Marksmen Roundtrip Snapshots</title>
  <style>
    body {{ font-family: sans-serif; margin: 2rem; background: #f5f5f5; }}
    h1 {{ color: #333; }}
    .grid {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 1rem; margin-top: 1rem; }}
    .card {{ background: white; border-radius: 6px; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,.15); }}
    h2 {{ margin: 0 0 .5rem; font-size: 1rem; color: #555; }}
    iframe {{ width: 100%; height: 600px; border: 1px solid #ddd; }}
    a.dl {{ display: inline-block; margin-top: .5rem; font-size: .85rem; color: #0366d6; }}
    .meta {{ font-size: .8rem; color: #888; margin-top: .25rem; }}
  </style>
</head>
<body>
  <h1>Marksmen Roundtrip Visual Snapshots</h1>
  <p>Generated from <code>demo.md</code> — open in a browser to inspect formatting.</p>
  <div class="grid">
    <div class="card">
      <h2>PDF Output</h2>
      <iframe src="demo_output.pdf" title="PDF Output"></iframe>
      <a class="dl" href="demo_output.pdf" download>Download PDF</a>
      <p class="meta">{pdf_bytes} bytes</p>
    </div>
    <div class="card">
      <h2>DOCX Output</h2>
      <p style="color:#666;font-size:.9rem">DOCX cannot be embedded in-browser. Download to inspect.</p>
      <a class="dl" href="demo_output.docx" download>Download DOCX</a>
      <p class="meta">{docx_bytes} bytes</p>
    </div>
    <div class="card">
      <h2>ODT Output</h2>
      <p style="color:#666;font-size:.9rem">ODT cannot be embedded in-browser. Download to inspect.</p>
      <a class="dl" href="demo_output.odt" download>Download ODT</a>
      <p class="meta">{odt_bytes} bytes</p>
    </div>
  </div>
</body>
</html>
"#,
        pdf_bytes = pdf_bytes.len(),
        docx_bytes = docx_bytes.len(),
        odt_bytes = odt_bytes.len(),
    );
    let viewer_path = snapshots_dir.join("index.html");
    fs::write(&viewer_path, viewer_html)?;
    println!("HTML → {} (open in browser for visual review)", viewer_path.display());

    Ok(())
}

/// Manual debugging aid — print the AST for an inline HTML snippet.
/// Run explicitly with: `cargo test test_ast_dump -- --ignored --nocapture`
#[test]
#[ignore]
fn test_ast_dump() {
    let md = "- **Underline**: <u style=\"color:red\">This text is underlined</u> via `<u>`";
    let events = marksmen_core::parsing::parser::parse(md);
    for e in &events {
        println!("{:?}", e);
    }
}

/// Manual debugging aid — extract `demo_test.docx` back to Markdown and save to
/// `extracted_manual.md`.  Requires `demo_test.docx` at the workspace root.
/// Run explicitly with: `cargo test test_manual_docx_extract -- --ignored --nocapture`
#[test]
#[ignore]
fn test_manual_docx_extract() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let docx_path = root.join("../../demo_test.docx");
    let bytes = std::fs::read(&docx_path)
        .unwrap_or_else(|_| panic!("demo_test.docx not found at {}", docx_path.display()));
    let text = marksmen_docx_read::parse_docx(&bytes, None).unwrap();
    let out = root.join("extracted_manual.md");
    std::fs::write(&out, &text).unwrap();
    println!("Written to {}", out.display());
}

/// Convert PRD/PRD.md to PDF and extract existing PRD DOCX files to MD.
#[test]
fn execute_prd_conversion() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../");
    println!("Workspace Root: {}", root.display());

    // 1. Convert PRD.md to PDF
    let prd_md_path = root.join("PRD/PRD.md");
    if prd_md_path.exists() {
        let prd_md_text = std::fs::read_to_string(&prd_md_path)?;
        let config = marksmen_core::Config::default();
        let pdf_bytes = marksmen_pdf::convert(&prd_md_text, &config, Some(root.join("PRD")))?;
        let pdf_out = root.join("PRD/PRD.pdf");
        std::fs::write(&pdf_out, pdf_bytes)?;
        println!("Compiled PRD.md -> {}", pdf_out.display());
    } else {
        println!("Warning: PRD/PRD.md not found.");
    }

    // 2. Convert Docx's to MD
    let docs = vec![
        "PRD/Product Requirement (PRD) - Transcranial 01.09.26 MS.docx",
        "PRD/Revised PRD Draft.docx",
    ];

    for doc in docs {
        let doc_path = root.join(doc);
        if doc_path.exists() {
            let bytes = std::fs::read(&doc_path)?;
            let md_text = marksmen_docx_read::parse_docx(&bytes, None)?;
            let md_out = doc_path.with_extension("md");
            std::fs::write(&md_out, md_text)?;
            println!("Extracted {} -> {}", doc, md_out.display());
        } else {
            println!("Warning: {} not found.", doc);
        }
    }

    Ok(())
}

#[test]
fn evaluate_prd_docx_roundtrip() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../");
    println!("Workspace Root: {}", root.display());

    let prd_md_path = root.join("PRD/PRD.md");
    if !prd_md_path.exists() {
        println!("Warning: PRD/PRD.md not found.");
        return Ok(());
    }

    let source_md = std::fs::read_to_string(&prd_md_path)?;
    
    // 1. Convert to DOCX
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&source_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    let docx_bytes = marksmen_docx::translation::document::convert(events, &config, &root.join("PRD"), None)?;

    // 2. Dump DOCX for manual reference
    let docx_out = root.join("PRD/prd.docx");
    std::fs::write(&docx_out, &docx_bytes)?;

    // 3. Extract back from DOCX to MD
    let extracted_md = marksmen_docx_read::parse_docx(&docx_bytes, None)?;
    
    // 4. Dump Markdown for discrepancy analysis
    let md_out = root.join("PRD/PRD_Roundtrip_Extracted.md");
    std::fs::write(&md_out, &extracted_md)?;

    let source_stripped = strip_mermaid(&strip_frontmatter(&source_md));
    let extracted_stripped = strip_mermaid(&strip_frontmatter(&extracted_md));

    let normalized_source = strip_vectors_and_html(&normalize_whitespace(&source_stripped));
    let normalized_extracted = strip_vectors_and_html(&normalize_whitespace(&extracted_stripped));

    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    println!("PRD DOCX Roundtrip Jaro-Winkler Similarity: {:.4}", jw_sim);

    std::fs::write(root.join("PRD/diff_norm_ext.txt"), &normalized_extracted)?;

    Ok(())
}

#[test]
fn test_html_conversion() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let demo_md = std::fs::read_to_string(root.join("../../demo.md"))?;
    
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    
    let html_string = marksmen_html::convert(events, &config)?;
    
    // Validate output bounds
    assert!(html_string.contains("<!DOCTYPE html>"), "Missing HTML DOCTYPE");
    assert!(html_string.contains("<svg"), "Missing inline Mermaid SVG injection");
    assert!(html_string.contains("<table"), "Missing Table parsing bounds");
    
    let snapshots_dir = root.join("tests/snapshots");
    std::fs::create_dir_all(&snapshots_dir)?;
    let html_out = snapshots_dir.join("demo_output_target.html");
    std::fs::write(&html_out, html_string)?;
    
    println!("HTML exported -> {}", html_out.display());
    Ok(())
}

/// Lossless structural roundtrip for the QSR Technical SonALAsense document.
///
/// Invariants verified:
///   1. `word/styles.xml` size ≥ 40,000 B  (full original catalogue reinstated)
///   2. `word/numbering.xml` size ≥ 30,000 B  (complex numbering reinstated)
///   3. `word/header1.xml` present  (header passthrough)
///   4. `word/footer1.xml` present  (footer passthrough)
///   5. `word/commentsIds.xml` present  (comment-ID anchor passthrough)
///   6. ≥ 7 distinct `w:id` values in `word/comments.xml`
///   7. Author "Lenora Henry" preserved in comments
///   8. Jaro-Winkler(extracted-from-original, extracted-from-roundtrip) ≥ 0.97
#[test]
fn test_qsr_lossless_roundtrip() -> Result<()> {
    use std::io::Read;

    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../");
    let src_path = root.join("PRD/QSR Technical_SonALAsense_1AY2AX000034_2026_APR.docx");

    if !src_path.exists() {
        println!("QSR source DOCX not found at {}; skipping test.", src_path.display());
        return Ok(());
    }

    let source_bytes = fs::read(&src_path)?;

    // ── 1. Extract original to Markdown (with media extraction) ───────────────
    let prd_dir = root.join("PRD");
    let media_dir = prd_dir.join("QSR_media");
    let _ = fs::create_dir_all(&media_dir);
    let intermediate_md = marksmen_docx_read::parse_docx(&source_bytes, Some(media_dir.as_path()))?;
    fs::write(prd_dir.join("QSR_Intermediate_RT.md"), &intermediate_md)?;

    // ── 2. Parse Markdown to AST ──────────────────────────────────────────────
    let config = marksmen_core::Config::default();
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&intermediate_md)?;
    let events = marksmen_core::parsing::parser::parse(body);

    // ── 3. Write DOCX with source-passthrough active ──────────────────────────
    let out_bytes = marksmen_docx::translation::document::convert(
        events,
        &config,
        &prd_dir,
        Some(&source_bytes),
    )?;
    fs::write(prd_dir.join("QSR_Roundtrip.docx"), &out_bytes)?;

    // ── 4. Structural assertions on output ZIP ────────────────────────────────
    let mut out_zip =
        zip::ZipArchive::new(std::io::Cursor::new(&out_bytes)).expect("output not a valid ZIP");

    // 4a. styles.xml size
    {
        let styles_size = out_zip.by_name("word/styles.xml")
            .expect("word/styles.xml missing from roundtrip")
            .size();
        assert!(
            styles_size >= 40_000,
            "word/styles.xml too small after passthrough: {} B (expected ≥ 40,000)",
            styles_size
        );
    }

    // 4b. numbering.xml size
    {
        let num_size = out_zip.by_name("word/numbering.xml")
            .expect("word/numbering.xml missing from roundtrip")
            .size();
        assert!(
            num_size >= 30_000,
            "word/numbering.xml too small after passthrough: {} B (expected ≥ 30,000)",
            num_size
        );
    }

    // 4c. Presence of header/footer/commentsIds
    assert!(
        out_zip.by_name("word/header1.xml").is_ok(),
        "word/header1.xml absent from roundtrip output"
    );
    assert!(
        out_zip.by_name("word/footer1.xml").is_ok(),
        "word/footer1.xml absent from roundtrip output"
    );
    assert!(
        out_zip.by_name("word/commentsIds.xml").is_ok(),
        "word/commentsIds.xml absent from roundtrip output"
    );

    // 4d. Comment count and author preservation
    {
        let mut comments_xml = String::new();
        out_zip
            .by_name("word/comments.xml")
            .expect("word/comments.xml missing")
            .read_to_string(&mut comments_xml)?;

        // Count distinct w:id values inside <w:comment ...> opening tags only.
        let id_re = regex::Regex::new(r#"<w:comment\s[^>]*?w:id="([^"]+)""#).unwrap();
        let distinct_ids: std::collections::HashSet<String> = id_re
            .captures_iter(&comments_xml)
            .map(|c| c[1].to_string())
            .collect();
        assert!(
            distinct_ids.len() >= 7,
            "Expected ≥ 7 distinct comment IDs; got {} ({:?})",
            distinct_ids.len(),
            distinct_ids
        );

        assert!(
            comments_xml.contains("Lenora Henry"),
            "Author 'Lenora Henry' not preserved in roundtrip comments.xml"
        );
    }

    // ── 5. Semantic similarity ────────────────────────────────────────────────
    let rt_extracted = marksmen_docx_read::parse_docx(&out_bytes, None)?;
    let orig_extracted = marksmen_docx_read::parse_docx(&source_bytes, None)?;

    // Strip header/footer sentinel blocks before comparison.
    // When source_docx passthrough is active, header1.xml is passed through verbatim
    // and the reader also picks it up from the XML ZIP entry. The body may contain
    // a duplicate text fragment from the <header> MD sentinel. Strip both to compare
    // only body-content similarity.
    fn strip_header_footer_blocks(s: &str) -> String {
        let mut out = String::with_capacity(s.len());
        let mut depth = 0usize;
        let mut i = 0;
        let bytes = s.as_bytes();
        while i < bytes.len() {
            if bytes[i..].starts_with(b"<header") { depth += 1; i += 7; continue; }
            if bytes[i..].starts_with(b"</header>") {
                if depth > 0 { depth -= 1; }
                i += 9; continue;
            }
            if bytes[i..].starts_with(b"<footer") { depth += 1; i += 7; continue; }
            if bytes[i..].starts_with(b"</footer>") {
                if depth > 0 { depth -= 1; }
                i += 9; continue;
            }
            if depth == 0 {
                out.push(bytes[i] as char);
            }
            i += 1;
        }
        out
    }

    let norm_rt = normalize_whitespace(&strip_vectors_and_html(&strip_header_footer_blocks(&rt_extracted)));
    let norm_orig = normalize_whitespace(&strip_vectors_and_html(&strip_header_footer_blocks(&orig_extracted)));

    // Remove table separator characters ('|') from both strings before JW comparison.
    // JW is a character-transposition metric: repeated '|' chars in table-rich documents
    // produce artificially low scores even when the semantic content is identical.
    // Single-character differences in '|' insertion cause large JW degradation.
    fn strip_table_pipes(s: &str) -> String {
        s.chars().filter(|c| *c != '|').collect()
    }

    let jw_orig = strip_table_pipes(&norm_orig);
    let jw_rt = strip_table_pipes(&norm_rt);

    fs::write(root.join("PRD/qsr_norm_orig.txt"), &norm_orig)?;
    fs::write(root.join("PRD/qsr_norm_rt.txt"), &norm_rt)?;

    let similarity = strsim::normalized_levenshtein(&jw_orig, &jw_rt);
    println!("QSR Lossless Roundtrip normalized-Levenshtein: {:.4}", similarity);

    assert!(
        similarity > 0.97,
        "QSR roundtrip text similarity {:.4} is below threshold 0.97",
        similarity
    );

    Ok(())
}

#[test]
fn test_qsr_pdf_roundtrip() -> Result<()> {
    use std::io::Read;

    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../");
    let src_path = root.join("PRD/QSR Technical_SonALAsense_1AY2AX000034_2026_APR.docx");

    if !src_path.exists() {
        println!("QSR source DOCX not found at {}; skipping test.", src_path.display());
        return Ok(());
    }

    let source_bytes = fs::read(&src_path)?;

    // ── 1. Extract original to Markdown (with media extraction) ───────────────
    let prd_dir = root.join("PRD");
    let media_dir = prd_dir.join("QSR_media");
    let _ = fs::create_dir_all(&media_dir);
    let intermediate_md = marksmen_docx_read::parse_docx(&source_bytes, Some(media_dir.as_path()))?;

    // ── 2. Convert Markdown to PDF ────────────────────────────────────────────
    let config = marksmen_core::Config::default();
    let pdf_bytes = marksmen_pdf::convert(&intermediate_md, &config, Some(prd_dir.clone()))?;
    fs::write(prd_dir.join("QSR_Intermediate_RT.pdf"), &pdf_bytes)?;

    // ── 3. Extract PDF back to Markdown ───────────────────────────────────────
    let pdf_extracted_md = marksmen_pdf_read::parse_pdf(&pdf_bytes)?;

    // ── 4. Parse Extracted Markdown to AST ────────────────────────────────────
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&pdf_extracted_md)?;
    let events = marksmen_core::parsing::parser::parse(body);

    // ── 5. Write DOCX from AST ────────────────────────────────────────────────
    let out_bytes = marksmen_docx::translation::document::convert(
        events,
        &config,
        &prd_dir,
        Some(&source_bytes),
    )?;
    fs::write(prd_dir.join("QSR_PDF_Roundtrip.docx"), &out_bytes)?;

    // ── 6. Semantic similarity ────────────────────────────────────────────────
    let rt_extracted = marksmen_docx_read::parse_docx(&out_bytes, None)?;
    let orig_extracted = marksmen_docx_read::parse_docx(&source_bytes, None)?;

    fn strip_header_footer_blocks(s: &str) -> String {
        let mut out = String::with_capacity(s.len());
        let mut depth = 0usize;
        let mut i = 0;
        let bytes = s.as_bytes();
        while i < bytes.len() {
            if bytes[i..].starts_with(b"<header") { depth += 1; i += 7; continue; }
            if bytes[i..].starts_with(b"</header>") {
                if depth > 0 { depth -= 1; }
                i += 9; continue;
            }
            if bytes[i..].starts_with(b"<footer") { depth += 1; i += 7; continue; }
            if bytes[i..].starts_with(b"</footer>") {
                if depth > 0 { depth -= 1; }
                i += 9; continue;
            }
            if depth == 0 {
                out.push(bytes[i] as char);
            }
            i += 1;
        }
        out
    }

    let norm_rt = normalize_whitespace(&strip_vectors_and_html(&strip_header_footer_blocks(&rt_extracted)));
    let norm_orig = normalize_whitespace(&strip_vectors_and_html(&strip_header_footer_blocks(&orig_extracted)));

    fn strip_table_pipes(s: &str) -> String {
        s.chars().filter(|c| *c != '|').collect()
    }

    let jw_orig = strip_table_pipes(&norm_orig);
    let jw_rt = strip_table_pipes(&norm_rt);

    let similarity = strsim::normalized_levenshtein(&jw_orig, &jw_rt);
    println!("QSR PDF Roundtrip normalized-Levenshtein: {:.4}", similarity);

    assert!(
        similarity > 0.97,
        "QSR PDF roundtrip text similarity {:.4} is below threshold 0.97",
        similarity
    );

    Ok(())
}

#[test]
fn test_xhtml_roundtrip_similarity() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let demo_md = fs::read_to_string(root.join("../../demo.md"))?;
    let source_md_stripped = strip_frontmatter(&demo_md);
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    let out = marksmen_xhtml::convert(events, &config)?;
    let extracted_md = marksmen_xhtml_read::parse_xhtml(&out)?;
    let normalized_source = normalize_whitespace(&strip_vectors_and_html(&source_md_stripped));
    let normalized_extracted = normalize_whitespace(&strip_vectors_and_html(&extracted_md));
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    assert!(jw_sim > 0.90, "XHTML roundtrip text similarity {:.4} is below threshold 0.90", jw_sim);
    Ok(())
}

#[test]
fn test_ppt_roundtrip_similarity() -> Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let demo_md = "# Slide One\n\nContent paragraph.\n\n---\n\n# Slide Two\n\n- item 1\n- item 2\n";
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    let out_bytes = marksmen_ppt::convert(events, &config)?;
    let extracted_md = marksmen_ppt_read::parse_pptx(&out_bytes)?;
    let normalized_source = normalize_whitespace(demo_md);
    let normalized_extracted = normalize_whitespace(&extracted_md);
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    assert!(jw_sim > 0.85, "PPTX roundtrip text similarity {:.4} is below threshold 0.85", jw_sim);
    Ok(())
}

#[test]
fn test_typst_roundtrip_similarity() -> Result<()> {
    let demo_md = "# Title\n\nSome text here.";
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    let out_str = marksmen_typst::translator::translate(events, &config)?;
    let extracted_md = marksmen_typst_read::parse_typst(&out_str)?;
    let normalized_source = normalize_whitespace(demo_md);
    let normalized_extracted = normalize_whitespace(&extracted_md);
    println!("TYPST OUT:\n{}", out_str);
    println!("TYPST EXTRACTED:\n{}", extracted_md);
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    assert!(jw_sim > 0.85, "Typst roundtrip text similarity {:.4} is below threshold 0.85", jw_sim);
    Ok(())
}

#[test]
fn test_latex_roundtrip_similarity() -> Result<()> {
    let demo_md = "# Heading\n\nMath $x=y$ testing **bold**.";
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    let out_str = marksmen_latex::convert(events, &config)?;
    let extracted_md = marksmen_latex_read::parse_latex(&out_str)?;
    let normalized_source = normalize_whitespace(demo_md);
    let normalized_extracted = normalize_whitespace(&extracted_md);
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    assert!(jw_sim > 0.85, "LaTeX roundtrip text similarity {:.4} is below threshold 0.85", jw_sim);
    Ok(())
}

#[test]
fn test_marp_roundtrip_similarity() -> Result<()> {
    let demo_md = "# Slide 1\n\nBody paragraph.\n\n---\n\n# Slide 2\n\nMore text.";
    let (body, _) = marksmen_core::config::frontmatter::parse_frontmatter(&demo_md)?;
    let config = marksmen_core::Config::default();
    let events = marksmen_core::parsing::parser::parse(body);
    let out_str = marksmen_marp::convert(events, &config)?;
    let extracted_md = marksmen_marp_read::parse_marp(&out_str)?;
    let normalized_source = normalize_whitespace(demo_md);
    let normalized_extracted = normalize_whitespace(&extracted_md);
    let jw_sim = strsim::jaro_winkler(&normalized_source, &normalized_extracted);
    assert!(jw_sim > 0.95, "Marp roundtrip text similarity {:.4} is below threshold 0.95", jw_sim);
    Ok(())
}
